name: Nervace
layout_spectrum: 0.6874425131827593
typography_spectrum: 0.6514578298665583
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.7150953928939998
  lightness: 0.2138829140458256
  saturation: 0.49724668310955167
  rhythmicContrast: 0.26286007440648973
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a7066319-65f4-4268-8798-a6e0ccef8a98.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a7066319-65f4-4268-8798-a6e0ccef8a98.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
title: ''
description: ''
